version: '3.7'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    tty: true
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
