version: '3.7'

services:
  dynamodb-local:
    image: "amazon/dynamodb-local:${DYNAMODB_LOCAL_VERSION}"
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      # - "./docker/dynamodb:/home/dynamodblocal/data"
      - dynamodb-local-data-volume:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    env_file:
      - .env.dynamodb-local
    user: root

  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:${DYNAMODB_ADMIN_VERSION}"
    container_name: dynamodb-admin
    env_file:
      - .env.dynamodb-admin

volumes:
  dynamodb-local-data-volume:
    driver: local
